apiVersion: v1
kind: Service
metadata:
  name: foodiesyelpnp-srv
spec:
  type: NodePort
  selector:
    app: foodiesyelp
  ports:
    - name: foodiesyelp
      protocol: TCP
      port: 8080
      targetPort: 8080